resolver 127.0.0.11 valid=5s ipv6=off;

upstream inventory_lab {
  zone inventory_lab 64k;
  server app:3000 resolve;
}

server {
  listen 80;

  location / {
    proxy_pass http://inventory_lab;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Request-Id $http_x_request_id;
  }
}
